[package]
name = "hybrid-logical-clock"
version = "0.0.1"
edition = "2021"
description = "A Rust implementation of Hybrid Logical Clocks for distributed systems"
license = "MIT"
repository = "https://github.com/zamderax/hybrid-logical-clock"

[dependencies]